@GenAiPlatform.FrontendApi_HostAddress = http://localhost:5173

GET {{GenAiPlatform.FrontendApi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{GenAiPlatform.FrontendApi_HostAddress}}/api/health

###
