version: '3.4'

services:
  frontendapi.genaiplatform:
    image: ${DOCKER_REGISTRY-}genaiplatformfrontendapi
    hostname: frontendapi.genaiplatform
    build:
      context: .
      dockerfile: frontendApi/Dockerfile

  summarization.genaiplatform:
    image: ${DOCKER_REGISTRY-}genaiplatformsummarizationapi
    build:
      context: .
      dockerfile: summarization/GenAiPlatformSummarizationApi/Dockerfile


  translation.genaiplatform:
    image: ${DOCKER_REGISTRY-}genaiplatformtranslation
    build:
      context: .
      dockerfile: translation/GenAiPlatform.Translation/Dockerfile

